version: "3.3"

services:
  db:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lumen

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile_nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
    - "80:80"
    depends_on:
      - db

  php:
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile_php
    volumes:
      - ./lumen:/var/www/html..
    working_dir: /var/www/html/app/public
    command: php-fpm
    links:
      - db:db
    ports:
      - "9000:9000"
    depends_on:
      - db